const plantInfo = [
  {
    id: '1',
    name: 'Aloe Vera',
    price: '250.00',
    imgURL: '../src/assets/plants/aloevera.png',
    description: 'Aloe Vera is a popular succulent known for its medicinal and air-purifying qualities.',
    lightRequirement: 'Bright, indirect sunlight',
    waterRequirement: 'Water every 2–3 weeks, allow soil to dry',
    careLevel: 'Easy',
    availability: 'In Stock',
    category: 'Succulents & Cacti',
  },
  {
    id: '2',
    name: 'Anthurium',
    price: '150.00',
    imgURL: '../src/assets/plants/anthurium.png',
    description: 'Anthurium is a tropical plant with glossy leaves and striking red flowers.',
    lightRequirement: 'Bright, indirect light',
    waterRequirement: 'Keep soil slightly moist',
    careLevel: 'Moderate',
    availability: 'In Stock',
    category: 'Flowering Plants',
  },
  {
    id: '3',
    name: 'Areca Palm',
    price: '500.00',
    imgURL: '../src/assets/plants/arecapalm.png',
    description: 'The Areca Palm is a tall indoor palm that adds a tropical vibe to your home.',
    lightRequirement: 'Filtered sunlight',
    waterRequirement: 'Water 2–3 times a week',
    careLevel: 'Moderate',
    availability: 'In Stock',
    category: 'Foliage Plants',
  },
  {
    id: '4',
    name: 'Cactus',
    price: '200.00',
    imgURL: '../src/assets/plants/aloevera.png',
    description: 'Cacti are low-maintenance plants ideal for sunny spots and minimal watering.',
    lightRequirement: 'Direct sunlight',
    waterRequirement: 'Once every 2–3 weeks',
    careLevel: 'Easy',
    availability: 'In Stock',
    category: 'Succulents & Cacti',
  },
  {
    id: '5',
    name: 'Echeveria',
    price: '350.00',
    imgURL: '../src/assets/plants/aloevera.png',
    description: 'Echeveria is a rosette-shaped succulent with a beautiful ornamental look.',
    lightRequirement: 'Bright sunlight',
    waterRequirement: 'Once a week',
    careLevel: 'Easy',
    availability: 'In Stock',
    category: 'Succulents & Cacti',
  },
  {
    id: '6',
    name: 'Jade',
    price: '150.00',
    imgURL: '../src/assets/plants/jade.png',
    description: 'The Jade Plant is a symbol of prosperity and is very easy to grow indoors.',
    lightRequirement: 'Bright light',
    waterRequirement: 'Water every 2–3 weeks',
    careLevel: 'Easy',
    availability: 'In Stock',
    category: 'Succulents & Cacti',
  },
  {
    id: '7',
    name: 'Lucky Bamboo',
    price: '250.00',
    imgURL: '../src/assets/plants/aloevera.png',
    description: 'Lucky Bamboo is believed to bring good luck and is easy to maintain in water or soil.',
    lightRequirement: 'Indirect light',
    waterRequirement: 'Change water weekly or keep soil moist',
    careLevel: 'Easy',
    availability: 'In Stock',
    category: 'Miniature Plants',
  },
  {
    id: '8',
    name: 'Money Plant',
    price: '150.00',
    imgURL: '../src/assets/plants/aloevera.png',
    description: 'The Money Plant is a popular indoor vine believed to bring prosperity.',
    lightRequirement: 'Low to medium light',
    waterRequirement: 'Water once a week',
    careLevel: 'Easy',
    availability: 'In Stock',
    category: 'Climbers & Vines',
  },
  {
    id: '9',
    name: 'Peace Lily',
    price: '200.00',
    imgURL: '../src/assets/plants/aloevera.png',
    description: 'The Peace Lily is an elegant plant with white blooms and excellent air-purifying ability.',
    lightRequirement: 'Low to bright indirect light',
    waterRequirement: 'Water when soil is dry',
    careLevel: 'Moderate',
    availability: 'In Stock',
    category: 'Flowering Plants',
  },
  {
    id: '10',
    name: 'Pothos',
    price: '300.00',
    imgURL: '../src/assets/plants/aloevera.png',
    description: 'Pothos is a hardy trailing vine that thrives in a variety of light conditions.',
    lightRequirement: 'Low to bright light',
    waterRequirement: 'Once a week',
    careLevel: 'Easy',
    availability: 'In Stock',
    category: 'Climbers & Vines',
  },
  {
    id: '11',
    name: 'Snake Plant',
    price: '350.00',
    imgURL: '../src/assets/plants/aloevera.png',
    description: 'The Snake Plant is one of the easiest houseplants to grow and is very tolerant.',
    lightRequirement: 'Low to bright indirect light',
    waterRequirement: 'Every 2–3 weeks',
    careLevel: 'Easy',
    availability: 'In Stock',
    category: 'Foliage Plants',
  },
  {
    id: '12',
    name: 'Spider Plant',
    price: '250.00',
    imgURL: '../src/assets/plants/aloevera.png',
    description: 'Spider Plants are fast-growing with striped leaves and air-purifying benefits.',
    lightRequirement: 'Indirect light',
    waterRequirement: 'Keep soil slightly moist',
    careLevel: 'Easy',
    availability: 'In Stock',
    category: 'Foliage Plants',
  },
  {
    id: '13',
    name: 'ZZ Plant',
    price: '180.00',
    imgURL: '../src/assets/plants/aloevera.png',
    description: 'The ZZ Plant is nearly indestructible and tolerates neglect, making it perfect for beginners.',
    lightRequirement: 'Low to bright indirect light',
    waterRequirement: 'Every 2–3 weeks',
    careLevel: 'Easy',
    availability: 'In Stock',
    category: 'Miniature Plants',
  },
]

export default plantInfo
